"""add checks

Revision ID: 281378b96797
Revises: f662239fe219
Create Date: 2024-05-01 16:24:48.371900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '281378b96797'
down_revision = 'f662239fe219'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'checks',
        sa.Column('uuid', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('user', postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user'], ['users.uuid'], name=op.f('fk_checks_user_users'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('uuid', name=op.f('pk_checks')),
    )
    op.create_table(
        'payments',
        sa.Column('uuid', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('check', postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['check'], ['checks.uuid'], name=op.f('fk_payments_check_checks'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('uuid', name=op.f('pk_payments')),
    )
    op.create_table(
        'products',
        sa.Column('uuid', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('check', postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['check'], ['checks.uuid'], name=op.f('fk_products_check_checks'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('uuid', name=op.f('pk_products')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('payments')
    op.drop_table('checks')
    # ### end Alembic commands ###
